<?php

// autoload_real.php @generated by Composer

class ApaiIOComposerAutoloaderInit
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Flowdee\Composer\Autoload\ApaiIOClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ApaiIOComposerAutoloaderInit', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Flowdee\Composer\Autoload\ApaiIOClassLoader();
        spl_autoload_unregister(array('ApaiIOComposerAutoloaderInit', 'loadClassLoader'));

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->set($namespace, $path);
        }

        $map = require __DIR__ . '/autoload_psr4.php';
        foreach ($map as $namespace => $path) {
            $loader->setPsr4($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register(true);

        return $loader;
    }
}

function composerRequire39e54938438d83822bf9edce55f42295($file)
{
    require $file;
}
